remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Regalos del javi]
description: [Página con los regalos del javi]
Additionally, you may choose to set the following optional variables:

show_downloads: true
